In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt

df=pd.read_csv(r'C:\Users\parth\Desktop\Data Mining and Knowledge Discovery\Project/covid.csv')

for i in df.columns:
    if i in ['id','entry_date','date_symptoms','date_died','age']:
        continue
    else:
        print('unique values in '+ i +' column- ',end=' ')
        print(df[i].unique())

date_cols=['entry_date','date_symptoms']
for dates in date_cols:
    df[dates]=pd.to_datetime(df[dates],infer_datetime_format=True)

df1=df
df['date_died'].replace('9999-99-99','Not Applicable',inplace=True)

df=df[['sex', 'patient_type', 'entry_date', 'date_symptoms', 'date_died', 'age',
       'intubed', 'pneumonia', 'pregnancy', 'diabetes', 'copd',
       'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular',
       'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid',
       'covid_res', 'icu']]

df.iloc[:,6:]=df.iloc[:,6:].replace([97,98,99],np.nan)
df.iloc[:,6:]=df.iloc[:,6:].replace(1,'Yes')
df.iloc[:,6:]=df.iloc[:,6:].replace(2,'No')

df.iloc[:,-2]=df.iloc[:,-2].replace('Yes','Positive')
df.iloc[:,-2]=df.iloc[:,-2].replace('No','Negative')
df.iloc[:,-2]=df.iloc[:,-2].replace(3,'Results awaited')

df=df[df['covid_res']!='Results awaited']

df

unique values in sex column-  [2 1]
unique values in patient_type column-  [1 2]
unique values in intubed column-  [97  2  1 99]
unique values in pneumonia column-  [ 2  1 99]
unique values in pregnancy column-  [97  2  1 98]
unique values in diabetes column-  [ 2  1 98]
unique values in copd column-  [ 2  1 98]
unique values in asthma column-  [ 2  1 98]
unique values in inmsupr column-  [ 2  1 98]
unique values in hypertension column-  [ 2  1 98]
unique values in other_disease column-  [ 2  1 98]
unique values in cardiovascular column-  [ 2  1 98]
unique values in obesity column-  [ 2  1 98]
unique values in renal_chronic column-  [ 2  1 98]
unique values in tobacco column-  [ 2  1 98]
unique values in contact_other_covid column-  [ 2 99  1]
unique values in covid_res column-  [1 2 3]
unique values in icu column-  [97  2  1 99]


C:\Users\parth\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


sex  patient_type entry_date date_symptoms       date_died  age  \
0         2             1 2020-04-05    2020-02-05  Not Applicable   27   
1         2             1 2020-03-19    2020-03-17  Not Applicable   24   
2         1             2 2020-06-04    2020-01-04  Not Applicable   54   
3         2             2 2020-04-17    2020-10-04  Not Applicable   30   
4         1             2 2020-04-13    2020-04-13      22-04-2020   60   
...     ...           ...        ...           ...             ...  ...   
499687    2             1 2020-03-26    2020-03-20  Not Applicable   77   
499688    2             2 2020-03-28    2020-03-23  Not Applicable   63   
499689    1             1 2020-03-16    2020-03-13  Not Applicable   25   
499690    1             1 2020-03-27    2020-03-25  Not Applicable   45   
499691    1             1 2020-03-31    2020-03-23  Not Applicable   51   

       intubed pneumonia pregnancy diabetes  ... inmsupr hypertension  \
0          NaN        No       NaN       No  ...      No           No   
1          NaN        No       NaN       No  ...      No           No   
2           No        No        No       No  ...      No           No   
3           No       Yes       NaN       No  ...      No           No   
4           No        No        No      Yes  ...      No          Yes   
...        ...       ...       ...      ...  ...     ...          ...   
499687     NaN       Yes       NaN       No  ...      No           No   
499688     Yes       Yes       NaN       No  ...      No          Yes   
499689     NaN        No        No       No  ...      No           No   
499690     NaN        No        No       No  ...      No          Yes   
499691     NaN        No        No       No  ...      No           No   

       other_disease cardiovascular obesity renal_chronic tobacco  \
0                 No             No      No            No      No   
1                 No             No      No            No      No   
2                 No             No     Yes            No      No   
3                 No             No      No            No      No   
4                 No            Yes      No            No      No   
...              ...            ...     ...           ...     ...   
499687           Yes             No      No            No     Yes   
499688            No             No     Yes            No     Yes   
499689            No             No      No            No      No   
499690            No             No      No            No      No   
499691            No             No      No            No      No   

       contact_other_covid covid_res  icu  
0                       No  Positive  NaN  
1                      NaN  Positive  NaN  
2                      NaN  Positive   No  
3                      NaN  Positive   No  
4                      NaN  Positive   No  
...                    ...       ...  ...  
499687                  No  Negative  NaN  
499688                  No  Negative   No  
499689                  No  Negative  NaN  
499690                 Yes  Negative  NaN  
499691                 NaN  Negative  NaN  

[499692 rows x 22 columns]

In [2]:
df

sex  patient_type entry_date date_symptoms       date_died  age  \
0         2             1 2020-04-05    2020-02-05  Not Applicable   27   
1         2             1 2020-03-19    2020-03-17  Not Applicable   24   
2         1             2 2020-06-04    2020-01-04  Not Applicable   54   
3         2             2 2020-04-17    2020-10-04  Not Applicable   30   
4         1             2 2020-04-13    2020-04-13      22-04-2020   60   
...     ...           ...        ...           ...             ...  ...   
499687    2             1 2020-03-26    2020-03-20  Not Applicable   77   
499688    2             2 2020-03-28    2020-03-23  Not Applicable   63   
499689    1             1 2020-03-16    2020-03-13  Not Applicable   25   
499690    1             1 2020-03-27    2020-03-25  Not Applicable   45   
499691    1             1 2020-03-31    2020-03-23  Not Applicable   51   

       intubed pneumonia pregnancy diabetes  ... inmsupr hypertension  \
0          NaN        No       NaN       No  ...      No           No   
1          NaN        No       NaN       No  ...      No           No   
2           No        No        No       No  ...      No           No   
3           No       Yes       NaN       No  ...      No           No   
4           No        No        No      Yes  ...      No          Yes   
...        ...       ...       ...      ...  ...     ...          ...   
499687     NaN       Yes       NaN       No  ...      No           No   
499688     Yes       Yes       NaN       No  ...      No          Yes   
499689     NaN        No        No       No  ...      No           No   
499690     NaN        No        No       No  ...      No          Yes   
499691     NaN        No        No       No  ...      No           No   

       other_disease cardiovascular obesity renal_chronic tobacco  \
0                 No             No      No            No      No   
1                 No             No      No            No      No   
2                 No             No     Yes            No      No   
3                 No             No      No            No      No   
4                 No            Yes      No            No      No   
...              ...            ...     ...           ...     ...   
499687           Yes             No      No            No     Yes   
499688            No             No     Yes            No     Yes   
499689            No             No      No            No      No   
499690            No             No      No            No      No   
499691            No             No      No            No      No   

       contact_other_covid covid_res  icu  
0                       No  Positive  NaN  
1                      NaN  Positive  NaN  
2                      NaN  Positive   No  
3                      NaN  Positive   No  
4                      NaN  Positive   No  
...                    ...       ...  ...  
499687                  No  Negative  NaN  
499688                  No  Negative   No  
499689                  No  Negative  NaN  
499690                 Yes  Negative  NaN  
499691                 NaN  Negative  NaN  

[499692 rows x 22 columns]

In [3]:
df.columns

Index(['sex', 'patient_type', 'entry_date', 'date_symptoms', 'date_died',
       'age', 'intubed', 'pneumonia', 'pregnancy', 'diabetes', 'copd',
       'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular',
       'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid',
       'covid_res', 'icu'],
      dtype='object')

Dropping date_died column as no relation with predicting covid positive.

Columns- pregnancy, intubed, contct_other_covid have more than 50% null values so dropping


In [4]:
df=df.drop(columns=['date_died','pregnancy','contact_other_covid','intubed','icu'])

### Feature Extraction from date-symptom and entry_date

In [5]:
df['delta']=abs(df['entry_date']-df['date_symptoms'])

In [6]:
df.loc[1,'delta']

Timedelta('2 days 00:00:00')

In [7]:
df['delta'] = df['delta'].dt.days.astype('int16')  #Converting Timedelta type to integer days

In [8]:
df['delta']

0          60
1           2
2         152
3         170
4           0
         ... 
499687      6
499688      5
499689      3
499690      2
499691      8
Name: delta, Length: 499692, dtype: int16

Dropping columns entry_date and date_symptoms

In [9]:
df=df.drop(columns=['entry_date','date_symptoms'])

In [10]:
df.columns

Index(['sex', 'patient_type', 'age', 'pneumonia', 'diabetes', 'copd', 'asthma',
       'inmsupr', 'hypertension', 'other_disease', 'cardiovascular', 'obesity',
       'renal_chronic', 'tobacco', 'covid_res', 'delta'],
      dtype='object')

In [11]:
len(df)

499692

There are few Null values present in columns that are categorical variables so we will drop Null values

In [12]:
df=df.dropna()

In [13]:
len(df)

496291

In [14]:
df

sex  patient_type  age pneumonia diabetes copd asthma inmsupr  \
0         2             1   27        No       No   No     No      No   
1         2             1   24        No       No   No     No      No   
2         1             2   54        No       No   No     No      No   
3         2             2   30       Yes       No   No     No      No   
4         1             2   60        No      Yes   No     No      No   
...     ...           ...  ...       ...      ...  ...    ...     ...   
499687    2             1   77       Yes       No   No     No      No   
499688    2             2   63       Yes       No   No     No      No   
499689    1             1   25        No       No   No     No      No   
499690    1             1   45        No       No   No     No      No   
499691    1             1   51        No       No   No     No      No   

       hypertension other_disease cardiovascular obesity renal_chronic  \
0                No            No             No      No            No   
1                No            No             No      No            No   
2                No            No             No     Yes            No   
3                No            No             No      No            No   
4               Yes            No            Yes      No            No   
...             ...           ...            ...     ...           ...   
499687           No           Yes             No      No            No   
499688          Yes            No             No     Yes            No   
499689           No            No             No      No            No   
499690          Yes            No             No      No            No   
499691           No            No             No      No            No   

       tobacco covid_res  delta  
0           No  Positive     60  
1           No  Positive      2  
2           No  Positive    152  
3           No  Positive    170  
4           No  Positive      0  
...        ...       ...    ...  
499687     Yes  Negative      6  
499688     Yes  Negative      5  
499689      No  Negative      3  
499690      No  Negative      2  
499691      No  Negative      8  

[496291 rows x 16 columns]

In [15]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [16]:
X_=df[['sex', 'patient_type', 'pneumonia', 'diabetes', 'copd', 'asthma',
       'inmsupr', 'hypertension', 'other_disease', 'cardiovascular', 'obesity',
       'renal_chronic', 'tobacco']]

In [17]:
oe.fit(X_)
X_=oe.transform(X_)

In [18]:
X_

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
import numpy as np
arr=np.array(df[['delta','age']])
arr

array([[ 60,  27],
       [  2,  24],
       [152,  54],
       ...,
       [  3,  25],
       [  2,  45],
       [  8,  51]], dtype=int64)

In [20]:
arr_=arr.reshape(496291,2)

In [21]:
X=np.append(arr_,X_,axis=1)

In [22]:
y=np.array(df['covid_res'])
y=y.reshape(-1,1)
oe.fit(y)
y=oe.transform(y)
# y.reshape(496291,1)
y

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [23]:
X

array([[ 60.,  27.,   1., ...,   0.,   0.,   0.],
       [  2.,  24.,   1., ...,   0.,   0.,   0.],
       [152.,  54.,   0., ...,   1.,   0.,   0.],
       ...,
       [  3.,  25.,   0., ...,   0.,   0.,   0.],
       [  2.,  45.,   0., ...,   0.,   0.,   0.],
       [  8.,  51.,   0., ...,   0.,   0.,   0.]])

In [24]:
from sklearn.model_selection import train_test_split
#Split into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=420)

## Decision Tree

In [25]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [30]:
y_pred = clf.predict(X_test)
y_train_pred=clf.predict(X_train)

In [31]:
# Model Accuracy, how often is the classifier correct?
from sklearn.metrics import accuracy_score
print("Test Accuracy:",accuracy_score(y_test, y_pred))
print("Train Accuracy:",accuracy_score(y_train, y_train_pred))

Test Accuracy: 0.6009940345713989
Train Accuracy: 0.7741628923894934


In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[70552, 20958],
       [44390, 27877]], dtype=int64)

In [40]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
print('Recall: ',recall_score(y_test,y_pred))
print('Precision: ',precision_score(y_test,y_pred))
print('F1 score: ',f1_score(y_test,y_pred))

Recall:  0.3857500657284791
Precision:  0.5708405856455411
F1 score:  0.46038876319135935


## Decision Forest

In [41]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_train_pred=clf.predict(X_train)
print("Test Accuracy:",accuracy_score(y_test, y_pred))
print("Train Accuracy:",accuracy_score(y_train, y_train_pred))
print('Recall: ',recall_score(y_test,y_pred))
print('Precision: ',precision_score(y_test,y_pred))
print('F1 score: ',f1_score(y_test,y_pred))

C:\Users\parth\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Test Accuracy: 0.6087057401222394
Train Accuracy: 0.7741448480364737
Recall:  0.43056996969571176
Precision:  0.5756891766882516
F1 score:  0.49266527862441317


## SVM

In [ ]:
#Linear SVC
from sklearn.svm import SVC
clf=SVC(kernel='linear')
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_train_pred=clf.predict(X_train)
print("Test Accuracy:",accuracy_score(y_test, y_pred))
print("Train Accuracy:",accuracy_score(y_train, y_train_pred))
print('Recall: ',recall_score(y_test,y_pred))
print('Precision: ',precision_score(y_test,y_pred))
print('F1 score: ',f1_score(y_test,y_pred))

C:\Users\parth\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [ ]:
#SVC with kernel=rbf
from sklearn.svm import SVC
clf=SVC(kernel='rbf')
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_train_pred=clf.predict(X_train)
print("Test Accuracy:",accuracy_score(y_test, y_pred))
print("Train Accuracy:",accuracy_score(y_train, y_train_pred))
print('Recall: ',recall_score(y_test,y_pred))
print('Precision: ',precision_score(y_test,y_pred))
print('F1 score: ',f1_score(y_test,y_pred))